default: &default
  oauth2:
    client_id: 572901801346-agcue25fuqh71ocj6u91eqih4psdp1n3.apps.googleusercontent.com
    client_secret: SXX64wVn8mePI_OshMhmOmis

development:
  <<: *default

production:
  <<: *default
